### ISSUE TITLE
lxpanel crashes when scrolling the plugin

### ISSUE THREAD

**Issue by nicoag328** [raspberrypi-ui/lxplug-volumepulse#3]
When the pulse volume is an odd number, and the speaker icon is scrolled down with the mouse wheel to 1, and then scrolled down one more time to get it to 0, lxpanel crashes.

Ran it in a terminal and got this error message:

```
** (lxpanel:12097): WARNING **: 02:56:09.575: set_sink_volume_by_name: err:3 Invalid argument

Assertion 'pthread_mutex_lock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:90, function pa_mutex_lock(). Aborting.
```

Then looked in the callback function for the scroll event:

```
    /* Update the PulseAudio volume by a step */
    int val = pulse_get_volume (vol);

    if (evt->direction == GDK_SCROLL_UP || evt->direction == GDK_SCROLL_LEFT)
    {
        if (val < 100) val += 2;
    }
    else
    {
        if (val > 0) val -= 2;
    }
    pulse_set_volume (vol, val);
```
It seems there is no limit for when the val is 1, so it becomes a negative number and crashes when trying to set the volume.
I want to fix it, but wasn't sure if I needed to open an issue first, as I'm a newbie on this.

**Comment by spl237** [comment]
Good catch! I'll fix that - many thanks for raising it.

**Comment by spl237** [comment]
Now fixed - updated version of the plugin should be in apt in the next day or so. Many thanks again.

**Comment by nicoag328** [comment]
Great! Thanks for the quick fix!
